version: 0.2

phases:
  install: 
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r simple-py-app/requirements.txt

  build:
    commands:
      - cd simple-py-app
      - echo "building docker image for app"
      - docker build -t "<>"
      - docker push <>

  post_build:
    commands:
      - echo "build done!"
