version: 0.2

env:
  parameter-store:
    DOCKER_CREDS_PWD: /simple-py-app/docker-creds/pwd
    DOCKER_CREDS_USERNAME: /simple-py-app/docker-creds/username


phases:
  install: 
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - pwd
      - ls -al
      - echo "building docker image for app"
      - docker build -t "docker.io/$DOCKER_CREDS_USERNAME/simple-py-be:latest" .
      - docker push "docker.io/$DOCKER_CREDS_USERNAME/simple-py-be:latest"

  post_build:
    commands:
      - echo "build done!"
